In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [2]:
homeprice = pd.read_csv('/Users/hackthebox/Downloads/Machine-Learning-Self-Study/ONE_HOT_ENCODING/Data/homeprices.csv')

In [4]:
homeprice.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [5]:
homeprice.columns

Index(['town', 'area', 'price'], dtype='object')

In [6]:
homeprice.shape

(13, 3)

In [7]:
homeprice.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   town    13 non-null     object
 1   area    13 non-null     int64 
 2   price   13 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 440.0+ bytes


In [10]:
homeprice['town'].value_counts()

town
monroe township    5
west windsor       4
robinsville        4
Name: count, dtype: int64

<div style="text-align: center; color: orange; font-size: 24px; font-weight: bold;">
    THE DUMMY VARIABLES METHOD
</div>

In [12]:
get_dummies = pd.get_dummies(homeprice['town'],dtype='int')
get_dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [13]:
get_dummies = get_dummies.drop(['west windsor'],axis='columns')
get_dummies

monroe township  robinsville
0                 1            0
1                 1            0
2                 1            0
3                 1            0
4                 1            0
5                 0            0
6                 0            0
7                 0            0
8                 0            0
9                 0            1
10                0            1
11                0            1
12                0            1

- Let us add these get_dummies variables to the original data frame using concat() method of pandas package.

In [14]:
merged = pd.concat([homeprice,get_dummies],axis='columns')
merged

town  area   price  monroe township  robinsville
0   monroe township  2600  550000                1            0
1   monroe township  3000  565000                1            0
2   monroe township  3200  610000                1            0
3   monroe township  3600  680000                1            0
4   monroe township  4000  725000                1            0
5      west windsor  2600  585000                0            0
6      west windsor  2800  615000                0            0
7      west windsor  3300  650000                0            0
8      west windsor  3600  710000                0            0
9       robinsville  2600  575000                0            1
10      robinsville  2900  600000                0            1
11      robinsville  3100  620000                0            1
12      robinsville  3600  695000                0            1

- In the above output,we do not require 'town' column as it is already replaced by the get_dummies variables (the last two columns).Hence let us the 'town' column.

In [15]:
final = merged.drop(['town'],axis='columns')
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

- This 'final' dataset should be used for analysis purpose.
- Now divided independent variables (x) and dependent variables(y).

In [16]:
x = final.drop(['price'],axis='columns')
y = final['price']

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [19]:
model.predict([[2800,1,0]]) # Moreno township

array([565089.22812299])

In [20]:
model.predict([[2800,0,1]]) # Robinsvile 

array([590775.63964739])

In [21]:
model.predict([[2800,0,0]]) # Neither Moreno township and Robinsvile

array([605103.20361213])

In [22]:
model.score(x,y)

0.9573929037221873

<div style="text-align: center; color: orange; font-size: 24px; font-weight: bold;">
    ONE HOT ENCODING METHOD
</div>

In [39]:
df = homeprice.copy()

In [40]:
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.town = le.fit_transform(df.town)
df

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [52]:
x = df[['town','area']].values
y = df['price']

In [53]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore')

In [54]:
x1 = ohe.fit_transform(df[['town']]) 
x1 = pd.DataFrame(x1.toarray())
x1

0    1    2
0   1.0  0.0  0.0
1   1.0  0.0  0.0
2   1.0  0.0  0.0
3   1.0  0.0  0.0
4   1.0  0.0  0.0
5   0.0  0.0  1.0
6   0.0  0.0  1.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  1.0  0.0
11  0.0  1.0  0.0
12  0.0  1.0  0.0

In [55]:
x1 = x1.iloc[:,1:]
x1

1    2
0   0.0  0.0
1   0.0  0.0
2   0.0  0.0
3   0.0  0.0
4   0.0  0.0
5   0.0  1.0
6   0.0  1.0
7   0.0  1.0
8   0.0  1.0
9   1.0  0.0
10  1.0  0.0
11  1.0  0.0
12  1.0  0.0

In [56]:
x = pd.concat([df, x1],axis='columns')
x

town  area   price    1    2
0      0  2600  550000  0.0  0.0
1      0  3000  565000  0.0  0.0
2      0  3200  610000  0.0  0.0
3      0  3600  680000  0.0  0.0
4      0  4000  725000  0.0  0.0
5      2  2600  585000  0.0  1.0
6      2  2800  615000  0.0  1.0
7      2  3300  650000  0.0  1.0
8      2  3600  710000  0.0  1.0
9      1  2600  575000  1.0  0.0
10     1  2900  600000  1.0  0.0
11     1  3100  620000  1.0  0.0
12     1  3600  695000  1.0  0.0

In [57]:
x.drop(['town','price'],axis='columns',inplace=True)

In [58]:
x

area    1    2
0   2600  0.0  0.0
1   3000  0.0  0.0
2   3200  0.0  0.0
3   3600  0.0  0.0
4   4000  0.0  0.0
5   2600  0.0  1.0
6   2800  0.0  1.0
7   3300  0.0  1.0
8   3600  0.0  1.0
9   2600  1.0  0.0
10  2900  1.0  0.0
11  3100  1.0  0.0
12  3600  1.0  0.0

In [61]:
x = x.values

In [59]:
from sklearn.linear_model import LinearRegression

In [62]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [63]:
model.predict([[2800,1,0]])

array([590775.63964739])

In [64]:
model.score(x,y)

0.9573929037221872