In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import joblib
from sklearn.datasets import load_iris

In [22]:
data = load_iris()

In [23]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [24]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [25]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
df['target'] = data.target

In [27]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [29]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [30]:
df['target'].map({i:name for i,name in enumerate(data.target_names) })

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object

In [31]:
df['target_names'] = df['target'].map({i:name for i,name in enumerate(data.target_names) })

In [32]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [33]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [37]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [38]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [39]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [42]:
binary_df = df[df['target'] != 2]

In [44]:
x_binary = binary_df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y_binary = binary_df['target']

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x_binary,y_binary,test_size=0.2,random_state=40)

In [49]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.485000          3.082500           2.950000   
std             0.646725          0.461361           1.462268   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.000000           3.300000   
75%             5.925000          3.400000           4.400000   
max             7.000000          4.100000           5.100000   

       petal width (cm)  
count         80.000000  
mean           0.826250  
std            0.573849  
min            0.100000  
25%            0.200000  
50%            1.000000  
75%            1.300000  
max            1.800000

In [50]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [51]:
x_train_scaled

array([[ 1.26814653, -1.27053324,  1.34195845,  1.18149775],
       [ 0.17894092, -0.17994677,  1.06668492,  1.18149775],
       [ 0.17894092, -1.27053324,  0.65377463,  0.48005196],
       [ 0.49014253, -0.83429865,  0.79141139,  0.30469052],
       [-0.75466389,  0.69252241, -0.92904816, -0.74747817],
       [ 1.11254573, -1.92488512,  1.06668492,  1.18149775],
       [ 1.89054974, -0.17994677,  1.41077683,  1.53222065],
       [-1.22146629,  0.25628782, -1.1355033 , -1.09820107],
       [ 2.04615054, -0.61618136,  1.27314007,  1.00613631],
       [ 0.02334012, -1.48865053,  0.58495625,  0.48005196],
       [-0.13226068,  0.69252241, -0.86022977, -1.09820107],
       [-0.44346228,  2.21934346, -0.99786654, -1.27356251],
       [ 1.42374733,  0.25628782,  1.06668492,  1.18149775],
       [-0.59906309,  0.9106397 , -1.06668492, -1.09820107],
       [ 1.57934814, -0.61618136,  1.1355033 ,  1.18149775],
       [-0.13226068,  1.34687429, -0.99786654, -1.09820107],
       [ 0.02334012,  0.

In [62]:
svm_binary = SVC(kernel='linear',C=1.0,probability=True)
svm_binary.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [63]:
svm_binary.predict(x_test_scaled)

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [64]:
print(classification_report(y_test,svm_binary.predict(x_test_scaled)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [65]:
confusion_matrix(y_test,svm_binary.predict(x_test_scaled))

array([[12,  0],
       [ 0,  8]])

In [66]:
joblib.dump(svm_binary,'svm_binary.pkl')

['svm_binary.pkl']

In [67]:
x_multi = df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y_multi = df['target']

In [68]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [70]:
y_multi.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [71]:
x_train_multi,x_test_multi,y_train_multi,y_test_multi = train_test_split(x_multi,y_multi,test_size=0.2,random_state=40)

In [72]:
svm_multi = SVC(kernel='linear')

In [73]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear')

In [74]:
svm_multi.predict(x_test_multi)

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])

In [76]:
print(classification_report(y_test_multi,svm_multi.predict(x_test_multi)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [77]:
confusion_matrix(y_test_multi,svm_multi.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]])

In [78]:
joblib.dump(svm_multi,'svm_multi.pkl')

['svm_multi.pkl']